name: awsdart
version: 0.0.0
author: Ole Martin Gjersvik
description: Library to work wit Amazone  Web Service.
dependencies:
  crypto: any
  intl: any
  log4dart: any
dev_dependencies:
  unittest: any
