name: awsdart
version: 0.0.2
author: Ole Martin Gjersvik <olem@olem.org>
description: Library to work wit Amazone  Web Service.
homepage: https://github.com/gjersvik/awsdart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.9.1'
  intl: '>=0.9.7 <0.9.8'
  log4dart: '>=1.4.12 <2.0.0'
dev_dependencies:
  unittest: any
