name: awsdart
version: 0.0.1
author: Ole Martin Gjersvik <olem@olem.org>
description: Library to work wit Amazone  Web Service.
homepage: https://github.com/gjersvik/awsdart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: any
  intl: any
  log4dart: any
dev_dependencies:
  unittest: any
